### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by Magnogen** [tetra-coder/ToadOS#1]
As this is an open source OS, the admin password is easily viewable. Could I suggest hashing it and comparing the hash of the value entered to the stored hash?

That way, people can't reverse engineer it and get the password. 🔐

**Comment by tetra-coder** [comment]
Yes, do it! I knew I could make an .env file, but I thought that might have some issues so I waited until you came.
The plan is great.

**Comment by tetra-coder** [comment]
Ok, I will try to do it. If I can't I will make an .env file and read that file.
Any questions?

**Comment by tetra-coder** [comment]
Yes, I already implemented it for the startup, for some reason it's not working for the main.py.
You can submit a PR.
