### ISSUE TITLE
Security: Don't distribute binaries in a repository

### ISSUE THREAD

**Issue by samclane** [tetra-coder/ToadOS#4]
I assume no bad intentions here, however, I still hesitate to run a random exe file, especially when a Python script tries to open it. This is because I cannot see the code inside like I can the Python scripts. If you made the game in Unity, then I know it can do "neutral" things like access the internet, or simply access my computer's username, without my consent. 

If you want to distribute your snake game, make a new repo with the source code, and include the binary under `Releases`. Then, we can work on a way to safely add the game to ToadOS (`sudo tpk  install snakegame` that takes you to the `Releases` page, as a start?)

**Comment by tetra-coder** [comment]
Just realized the snake game would sometimes crash and freeze your mouse, so I removed it.
I'll build a new one later to compensate.
